using OpenQA.Selenium;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FrameworkAutomation.PageObjectModel
{
    public class UserDetailsNEW
    {
        #region PageObjects
        public By Roles_ResponsibilitiesTable => By.XPath("/html/body/form/div[5]/div/div[2]/div[1]/div[5]/div/div[3]/div/div[3]/div[2]/div[3]/div[3]/div/div/table");
        public By OpenPermissionButtonMCFW => By.CssSelector("#MEDCHARTContent_MedchartPagesContent_ucMCFW_pnlPerms > div:nth-child(1) > input:nth-child(1)");
        public By OpenPermissionButtonECASE => By.CssSelector("#MEDCHARTContent_MedchartPagesContent_ucECASE_pnlPerms > div:nth-child(1) > input:nth-child(1)");                            
        public By SaveUserDetailsLink => By.Id("MEDCHARTContent_MedchartPagesContent_userInfoUserControl_UpdateButton");
        public By OkButton => By.CssSelector("div.ui-dialog:nth-child(7) > div:nth-child(3) > div:nth-child(1) > button:nth-child(1)");
        public By OkRoleButton => By.CssSelector("div.ui-dialog:nth-child(37) > div:nth-child(3) > div:nth-child(1) > button:nth-child(1)");
        public By RoleModal => By.CssSelector("#MEDCHARTContent_MedchartPagesContent_ucAVS_jqSelectRolesDialog > div:nth-child(1) > div:nth-child(1) > span:nth-child(1) > b:nth-child(1)");
        public By OkButtonAVS => By.CssSelector("div.ui-dialog:nth-child(38) > div:nth-child(3) > div:nth-child(1) > button:nth-child(1)");
        public By OkButtonAVSAllow => By.CssSelector("div.ui-dialog:nth-child(9) > div:nth-child(3) > div:nth-child(1) > button:nth-child(1)");
        public By OkButtonAVSDisallow => By.CssSelector("div.ui-dialog:nth-child(38) > div:nth-child(3) > div:nth-child(1) > button:nth-child(1)");
        public By Role_ResponsibilitiesTable => By.CssSelector("#MEDCHARTContent_MedchartPagesContent_ucECASE_RoleCheckBoxesDataList");
        public By Role_Resp_Framework => By.CssSelector("#MEDCHARTContent_MedchartPagesContent_ucMCFW_upRole > div:nth-child(3) > div:nth-child(1) > div:nth-child(2) > table:nth-child(1)");
        public By Role_ResponsibilitiesHRRTable => By.Id("MEDCHARTContent_MedchartPagesContent_ucHRR_RoleCheckBoxesDataList");
        public By Role_ResponsibilitiesAVSTable => By.Id("MEDCHARTContent_MedchartPagesContent_ucAVS_RoleCheckBoxesDataList");
        public By Role_AVS_manager => By.Id("MEDCHARTContent_MedchartPagesContent_ucAVS_RoleCheckBoxesDataList_RoleCheckBox_0");
        public By ECaseTab => By.Id("MEDCHARTContent_MedchartPagesContent_ucECASE_pnlPerms");
        //public By OpenPermissionFramework => By.Name("ctl00$ctl00$MEDCHARTContent$MedchartPagesContent$ucMCFW$btnPerm");
        public By DisallowLabel => By.CssSelector("#StatusSelectionRBList_HRR > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > label:nth-child(2)");
        public By DisallowLabelAVS => By.CssSelector("#StatusSelectionRBList_AVS > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > label:nth-child(2)");
        public By allowLabel => By.CssSelector("#StatusSelectionRBList_HRR > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > label:nth-child(2)");
        public By allowLabelDen => By.CssSelector("#StatusSelectionRBList_DenClass > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > label:nth-child(2)");
        public By allowLabelAVS => By.CssSelector("#StatusSelectionRBList_AVS > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1) > label:nth-child(2)");
        public By allowLabeleCase => By.CssSelector("#StatusSelectionRBList_eCase > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > label:nth-child(2)");
        public By allowLabeleMMPS => By.CssSelector("#StatusSelectionRBList_eMMPS > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > label:nth-child(2)");
        public By allowLabelMATS => By.CssSelector("#StatusSelectionRBList_MATS > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > label:nth-child(2)");
        public By allowLabelMRR => By.CssSelector("#StatusSelectionRBList_MRR > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > label:nth-child(2)");
        public By allowLabelOccHealth => By.CssSelector("#StatusSelectionRBList_OccHealth > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > label:nth-child(2)");
        public By disallowLabel => By.CssSelector("#StatusSelectionRBList_HRR > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(3) > label:nth-child(2)");
        public By disallowLabelDen => By.CssSelector("#StatusSelectionRBList_DenClass > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(3) > label:nth-child(2)");
        public By disallowlabelDen => By.CssSelector("#StatusSelectionRBList_DenClass > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > label:nth-child(2)");
        public By disallowlabelEcase => By.CssSelector("#StatusSelectionRBList_eCase > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > label:nth-child(2)");
        public By disallowLabelAVS => By.CssSelector("#StatusSelectionRBList_AVS > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > label:nth-child(2)");
        public By disallowLabeleCase => By.CssSelector("#StatusSelectionRBList_eCase > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(3) > label:nth-child(2)");
        public By disallowLabeleMMPS => By.CssSelector("#StatusSelectionRBList_eMMPS > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(3) > label:nth-child(2)");
        public By disallowLabelMATS => By.CssSelector("#StatusSelectionRBList_MATS > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(3) > label:nth-child(2)");
        public By disallowLabelMRR => By.CssSelector("#StatusSelectionRBList_MRR > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(3) > label:nth-child(2)");
        public By disallowLabelHRR => By.CssSelector("#StatusSelectionRBList_HRR > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(3) > label:nth-child(2)");
        public By disallowLabelOccHealth => By.CssSelector("#StatusSelectionRBList_OccHealth > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(3) > label:nth-child(2)");
        public By disapproveLabelHRR => By.CssSelector("#StatusSelectionRBList_HRR > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(3) > span:nth-child(1) > label:nth-child(2)");
        public By YesButton => By.CssSelector("div.ui-dialog:nth-child(37) > div:nth-child(3) > div:nth-child(1) > button:nth-child(1)");
        public By NoButton => By.CssSelector("div.ui-dialog:nth-child(37) > div:nth-child(3) > div:nth-child(1) > button:nth-child(2)");
        public By OKButton => By.CssSelector("div.ui-dialog:nth-child(38) > div:nth-child(3) > div:nth-child(1) > button:nth-child(1)");
        public By OpenPermissionButtonHRR => By.CssSelector("#MEDCHARTContent_MedchartPagesContent_ucHRR_pnlPerms > div:nth-child(1) > input:nth-child(1)");
        public By GoBackButton => By.Id("MEDCHARTContent_MedchartPagesContent_GoBackLinkButton");
        public By FirstnameTextbox => By.Id("FirstNameTextBox");
        public By LastnameTextbox => By.Id("LastNameTextBox");
        public By LastnameTextboxAVS => By.Id("MEDCHARTContent_MedchartPagesContent_LastNameTextBox");
        public By MiddlenameTextbox => By.Id("MiddleNameTextBox");
        public By RankDropdown => By.Id("RankDropDownList");
        public By OrganizationDropdown => By.Id("MEDCHARTContent_MedchartPagesContent_OrganizationDropDownList");
        public By ModuleDropdown => By.Id("MEDCHARTContent_MedchartPagesContent_ModuleDropDownList");
        public By ExtPermissionDropdown => By.Id("MEDCHARTContent_MedchartPagesContent_ExtendablePermissionDropDownList");
        public By RoleDropdown => By.Id("MEDCHARTContent_MedchartPagesContent_RoleDropDownList");
        public By RegionDropdownAVS => By.Id("MEDCHARTContent_MedchartPagesContent_RegionDropDownList");
        public By PrimaryNumberTextbox => By.Id("PrimaryNumberTextBox");
        public By SecondaryNumberTextbox => By.Id("SecondaryNumberTextBox");
        public By EmailAddressTextbox => By.Id("EmailAddressTextBox");
        public By PrimaryNumberExtensionTextbox => By.Id("PrimaryNumberExtensionTextBox");
        public By SecondaryNumberExtensionTextbox => By.Id("SecondaryNumberExtensionTextBox");
        public By DSNTextbox => By.Id("DSNTextBox");
        public By ApprovalTextbox => By.Id("MEDCHARTContent_MedchartPagesContent_ucHRR_CommentTextBox");
        public By ApprovalTextboxAVS => By.Id("MEDCHARTContent_MedchartPagesContent_ucAVS_CommentTextBox");
        public By ApprovalTextboxDen => By.Id("MEDCHARTContent_MedchartPagesContent_ucDENCLASS_CommentTextBox");
        public By ApprovalTextboxMATS => By.Id("MEDCHARTContent_MedchartPagesContent_ucMATS_CommentTextBox");
        public By ApprovalTextboxMRR => By.Id("MEDCHARTContent_MedchartPagesContent_ucMRR_CommentTextBox");
        public By ApprovalTextboxOccHealth => By.Id("MEDCHARTContent_MedchartPagesContent_ucOccHealth_CommentTextBox");
        public By ApprovalTextboxeCase => By.Id("MEDCHARTContent_MedchartPagesContent_ucECASE_CommentTextBox");
        public By ApprovalTextboxeMMPS => By.Id("MEDCHARTContent_MedchartPagesContent_uceMMPS_CommentTextBox");
        public By Modal => By.Id("MEDCHARTContent_MedchartPagesContent_divModalBackgroundParentWindow");
        public By SaveUserMessage => By.Id("MEDCHARTContent_MedchartPagesContent_userInfoUserControl_spnMsg");
        public By ModalText => By.Id("divModalText");
        public By PermissionTab => By.Id("PermissionAmendmentsTabContainer_header");
        public By DocMgmtTab => By.Id("__tab_PermissionAmendmentsTabContainer_hrrPermissionGroupTab_61");
        public By ReportsTab => By.Id("__tab_PermissionAmendmentsTabContainer_hrrPermissionGroupTab_63");
        public By BatchMgmtTab => By.Id("__tab_PermissionAmendmentsTabContainer_hrrPermissionGroupTab_62");
        public By HelpTab => By.Id("__tab_PermissionAmendmentsTabContainer_hrrPermissionGroupTab_64");
        public By HRRTab => By.Id("__tab_PermissionAmendmentsTabContainer_hrrPermissionGroupTab_65");
        public By SelectAllTabMedcharAdmin => By.Id("PermissionAmendmentsTabContainer_hrrPermissionGroupTab_1_SelectAllPermissionsButton_1");
        public By SelectAllTabDocMgt => By.Id("PermissionAmendmentsTabContainer_hrrPermissionGroupTab_61_SelectAllPermissionsButton_61");
        public By SelectAllTabBatchMgt => By.Id("PermissionAmendmentsTabContainer_hrrPermissionGroupTab_62_SelectAllPermissionsButton_62");
        public By SelectAllTabReport => By.Id("PermissionAmendmentsTabContainer_hrrPermissionGroupTab_63_SelectAllPermissionsButton_63");
        public By SelectAllTabHelp => By.Id("PermissionAmendmentsTabContainer_hrrPermissionGroupTab_64_SelectAllPermissionsButton_64");
        public By SelectAllTabHRR => By.Id("PermissionAmendmentsTabContainer_hrrPermissionGroupTab_65_SelectAllPermissionsButton_65");
        public By ClearAllButton => By.Id("btnClearAll");
        public By ResetButton => By.Id("btnReset");
        public By RegionDropdown => By.Id("MEDCHARTContent_MedchartPagesContent_ucHRR_RegionDropDownList");
        public By RoleOkButton => By.CssSelector("div.ui-dialog:nth-child(10) > div:nth-child(3) > div:nth-child(1) > button:nth-child(1)");
        public By CommentTextbox => By.Id("MEDCHARTContent_MedchartPagesContent_ucAVS_CommentTextBox");
        public By CommentTextboxDen => By.Id("MEDCHARTContent_MedchartPagesContent_ucDENCLASS_CommentTextBox");
        public By CommentTextboxEcase => By.Id("MEDCHARTContent_MedchartPagesContent_ucECASE_CommentTextBox");
        public By edipinlabel => By.Id("MEDCHARTContent_MedchartPagesContent_userInfoUserControl_EDIPILabel");
        public By edipinText => By.Id("MEDCHARTContent_MedchartPagesContent_EdipnTextBox");
        public By edipinAlert => By.Id("EdipinAlert");
        public By ViewUserDetails => By.Id("MEDCHARTContent_MedchartPagesContent_GetUserDetailsButton");
        public By MedchartTable => By.Id("pendingApprovalCountDiv");
        public By HIPAALink => By.Id("AvsHIPAAWaitingApprovalCountHyperLink");
        public By HIPAALinkDen => By.Id("DenClassHIPAAWaitingApprovalCountHyperLink");
        public By HIPAALinkEcase => By.Id("EcaseHIPAAWaitingApprovalCountHyperLink");
        public By HIPAALinkEmmps => By.Id("EmmpsHIPAAWaitingApprovalCountHyperLink");
        public By HIPAALinkHRR => By.Id("HRRHIPAAWaitingApprovalCountHyperLink");
        public By HIPAALinkMats => By.Id("MatsHIPAAWaitingApprovalCountHyperLink");
        public By HIPAALinkAcrc => By.Id("AcrcHIPAAWaitingApprovalCountHyperLink");
        public By HIPAALinkMrr => By.Id("MrrHIPAAWaitingApprovalCountHyperLink");
        public By HIPAALinkOcc => By.Id("OccHealthHIPAAWaitingApprovalCountHyperLink");
        public By RecordTable => By.Id("MEDCHARTContent_MedchartPagesContent_UserListGridView");
        public By ApproveHIPAA => By.Id("ApproveHipaaCertificateLinkButton");
        public By CalendarButton => By.CssSelector(".ui-datepicker-trigger");
        public By CalendarTable => By.CssSelector(".ui-datepicker-calendar > tbody:nth-child(2)");
        public By HIPAASubmitButton => By.Id("submitButtondlg");
        public By PendingApprovalCheckbox => By.Id("MEDCHARTContent_MedchartPagesContent_HipaaPendingApprovalUsersOnlyCheckBox");
        public By UserListGridviewHeader => By.Id("MEDCHARTContent_MedchartPagesContent_UserListGridView");
        public By LockoutChecbox => By.Id("MEDCHARTContent_MedchartPagesContent_LockedOutCheckBox");
        public By MedchartSysAdminCheckbox => By.Id("MEDCHARTContent_MedchartPagesContent_ucMCFW_RoleCheckBoxesDataList_RoleCheckBox_0");
        public By MedchartUsarManagerCheckbox => By.Id("MEDCHARTContent_MedchartPagesContent_ucMCFW_RoleCheckBoxesDataList_RoleCheckBox_2");
        public By MRRSysAdminCheckbox => By.Id("MEDCHARTContent_MedchartPagesContent_ucMRR_RoleCheckBoxesDataList_RoleCheckBox_0");
        public By MRRUSARManagerCheckbox => By.Id("MEDCHARTContent_MedchartPagesContent_ucMRR_RoleCheckBoxesDataList_RoleCheckBox_1");
        public By ECaseSysAdminCheckbox => By.Id("MEDCHARTContent_MedchartPagesContent_ucECASE_RoleCheckBoxesDataList_RoleCheckBox_0");
        public By ECaseARNGManagerCheckbox => By.Id("MEDCHARTContent_MedchartPagesContent_ucECASE_RoleCheckBoxesDataList_RoleCheckBox_1");
        public By OccHealthARNGManagerCheckbox => By.Id("MEDCHARTContent_MedchartPagesContent_ucOccHealth_RoleCheckBoxesDataList_RoleCheckBox_1");
        public By OccHealthSysAdminCheckbox => By.Id("MEDCHARTContent_MedchartPagesContent_ucOccHealth_RoleCheckBoxesDataList_RoleCheckBox_0");
        #endregion
    }
}
